version: '3'
services:

  #PHP Service
  xmlparser:
    build:
      context: .
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: xmlparser
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
