parameters:
  version: 1.0
  google_app_name: 'Google Sheets and PHP'
  google_scopes:
    - 'https://www.googleapis.com/auth/spreadsheets'
  google_access_type: 'offline'
#  google_auth_config: '%app_dir%/config/google/keys.json'
  log_path: '/tmp/project.log'
  log_level: 'error'

services:
  _defaults:
    autowire: true
    public: false
    bind:
      string $version: '%version%'
      $logger: '@Monolog\Logger'

  _instanceof:
    Symfony\Component\Console\Command\Command:
      tags: ['command']

  App\:
    resource: '../src/*'


  App\Application:
    public: true
    arguments:
      - !tagged_iterator command

  Google\Client:
    calls:
      - setApplicationName: ['%google_app_name%']
      - setScopes: ['%google_scopes%']
      - setAccessType: ['%google_access_type%']
#      - setAuthConfig: ['%google_auth_config%']

  Google\Service\Sheets:
    arguments:
      - '@Google\Client'

  Monolog\Handler\StreamHandler:
    arguments:
      - '%log_path%'
      - '%log_level%'

  Monolog\Logger:
    arguments: ['main']
    calls:
      - pushHandler: ['@Monolog\Handler\StreamHandler']